### ISSUE TITLE
Find a suitable API

### ISSUE THREAD

**Issue by ZathrasXI** [uob-group-10-mynt/banking-app#1]
See [the spreadsheet](https://uob-my.sharepoint.com/:x:/r/personal/gd23168_bristol_ac_uk/Documents/TB3-SummerProject/Custodian%20Bank%20Account%20options.xlsx?d=webb25b63d33a495787e35910ec1b52ea&csf=1&web=1&e=7yntLX) for details of the APIs.

Criteria: 
- [ ] Has an API that you have been able to test
- [ ] API has good documentation
- [ ] The bank offers Custodian Accounts/Custody Holdings
- [ ] The bank handles Kenyan Shillings
- [ ] API has ability for transferring money, getting transfer history, and if necessary/relevant creating sub-accounts

**Comment by koreanMike513** [comment]
[CurrencyCloud](https://developer.currencycloud.com/guides/getting-started/introduction/) seems to be the best available option for its:

- Main Account
- Sub Account Transfers
- Transfers to Beneficiaries

**Comment by ZathrasXI** [comment]
[Currency Cloud API repo](https://github.com/uob-group-10-mynt/API-Research)
commit #65b0735
